FROM ubuntu:22.04

WORKDIR /app

RUN apt-get update \
    && apt-get install -y python3 python3-pip \
    && pip3 install --no-cache-dir torch torchvision pillow \
    && rm -rf /var/lib/apt/lists/*

COPY model.pt inference.py db/test-img.jpg ./

CMD ["python3", "inference.py", "test-img.jpg"]